### ISSUE TITLE
Do you know any algorithms in Javascript?

### ISSUE THREAD

**Issue by abranhe** [abranhe/allalgorithms-js#3]
<p align="center">
  <img src="https://cdn.abranhe.com/projects/algorithms/algorithms.svg">
</p>

Hi, everyone!

I am creating this library and it would be great if you can help me to include some algorithms in it.

Wating to merge your pull request.

**Comment by evgenygil** [comment]
Good idea, I'll try to make some

**Comment by amaguma** [comment]
I'll try to implement some algorithms for graph search such as BFS, DFS, Dijkstra etc))

**Comment by abranhe** [comment]
@Gil707 @amaguma it would be great!

**Comment by evgenygil** [comment]
@abranhe in which branch I should merge? `master` or `adding-stuff`?

**Comment by abranhe** [comment]
@Gil707 

> @abranhe in which branch I should merge? `master` or `adding-stuff`?

On `mater` would be fine.
